name: flutter_slider
description: A simple carousel slider for personal use on flutter projects

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png

author: Alvin Lee <alvinlee001@live.com.my>
homepage: https://github.com/alvinlee001/page-transformer
version: 0.0.1
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
